name: gemini_ai_prototype
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^0.13.3
  http_interceptor: ^1.0.2
  logger: ^1.1.0
  cached_network_image: ^3.3.1
  google_fonts: ^4.0.0
  iconsax: ^0.0.8
  image_picker: ^1.0.7
  video_player: ^2.8.6
  dartz: ^0.10.1
  convert: ^3.1.1
  typed_data: ^1.3.2
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/